title: Postcode.eu Knowledge Base
description: Frequently Asked Questions about the Postcode.eu API
theme: jekyll-theme-minimal
markdown: GFM
permalink: /:slugified_categories/:slug

collections:
  categories:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "categories"
      type: "pages"
    values:
      layout: "default"
